all: to_string.example lexical_cast.example

to_string.example: std.cpp
	clang++ std.cpp -std=c++11 -o to_string.example

lexical_cast.example: std.cpp
	clang++ boost.cpp -std=c++11 -o lexical_cast.example
